# Generated by Django 5.1.4 on 2024-12-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_actor_actor_name_en_actor_actor_name_ru_actor_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
