# Generated by Django 5.1.4 on 2024-12-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_moments_movie_alter_movie_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(related_name='actor_movies', to='movie.actor'),
        ),
    ]
