# Generated by Django 5.1.4 on 2024-12-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_movie_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
